allow_remote_control socket-only
listen_on unix:/tmp/kitty

cursor_shape     block
shell_integration no-cursor
cursor_blink_interval 0.5

enabled_layouts splits

draw_minimal_borders      yes
sync_to_monitor no
strip_ansi_hyperlinks off

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'

map ctrl+s kitty_scrollback_nvim

map ctrl+space launch --cwd=current zed .
map ctrl+shift+t launch --type=tab --cwd=current
map alt+h launch --type=window --location=vsplit --cwd=current
map alt+l launch --type=window --location=hsplit --cwd=current
map alt+k next_window
map alt+j prev_window

map ctrl+y copy_selection_or_last_command_output

scrollback_lines 800

font_family      GeistMono NFM Light
bold_font        GeistMono NFM Light
italic_font      auto
bold_italic_font auto
font_size        15
modify_font line_height 130%

hide_window_decorations yes
confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Harper
include current-theme.conf
# END_KITTY_THEME
