allow_remote_control socket-only
listen_on unix:/tmp/kitty

cursor_shape     block
shell_integration no-cursor
cursor_blink_interval 0.5

draw_minimal_borders      yes
# repaint_delay 3
sync_to_monitor no
strip_ansi_hyperlinks off

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'

map ctrl+s kitty_scrollback_nvim

map ctrl+space launch --cwd=current zed .

map ctrl+y copy_selection_or_last_command_output

scrollback_lines 300

font_family      GeistMono NFM Light
bold_font        GeistMono NFM Light
italic_font      auto
bold_italic_font auto
font_size        14

hide_window_decorations yes

active_border_color       #bd93f9
inactive_border_color     #6272a4

# Make it looks like the COSMIC Terminal

# Core Colors
background            #000000
foreground            #cbd3cc
cursor                #cbd3dd
selection_background  #364456
selection_foreground  #ccd4e0

color0                #181a1f
color8                #4b5263

color1                #f2717a
color9                #f2717a

color2                #7bc293
color10               #7bc293

color3                #ddb67e
color11               #ddb67e

color4                #89b4fa
color12               #89b4fa

color5                #b48ead
color13               #b48ead

color6                #5faaba
color14               #5faaba

color7                #b5bcc6
color15               #cbd3dd
